sudo: required

language: java
jdk: jdk8

services:
  - docker

install:
  - mvn -f test validate
  - docker pull openjdk:8-jre-alpine

script:
  - ./build.sh
  - docker run -t -p 9444:9444 -d meteogroup/s3mock
  - mvn -f test test
